#### 배열 전치와 축 바꾸기

- 배열 전치 : 데이터를 복사하지 않고 데이터의 모양이 바뀐 뷰 반환
- `transpose`, `T`


In [1]:
arr = np.arange(15).reshape((3,5))

arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [2]:
arr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [3]:
arr = np.random.randn(6,3)

arr

array([[ 0.10140534, -0.44601326, -0.9558198 ],
       [-0.7710479 ,  0.20129207,  0.74681437],
       [ 0.34949719,  0.21429297, -0.4296694 ],
       [ 0.91309022,  0.55420569,  0.33166981],
       [ 1.01185925,  0.82673371, -0.60566889],
       [ 0.48423478,  0.59012522,  0.08802486]])

In [4]:
np.dot(arr.T, arr)

array([[ 2.81902241,  1.50279794, -1.09030564],
       [ 1.50279794,  1.62424816,  0.21959308],
       [-1.09030564,  0.21959308,  2.14052702]])

- 다차원 배열의 경우, transpose메서드는 튜플로 축 번호 받아서 치환

In [6]:
arr = np.arange(16).reshape((2, 2, 4))
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [7]:
# 1번째 축, 2번째 축 순서 변경됨

arr.transpose((1,0,2))

array([[[ 0,  1,  2,  3],
        [ 8,  9, 10, 11]],

       [[ 4,  5,  6,  7],
        [12, 13, 14, 15]]])

- `swapaxes` 메서드 : 2개의 축 번호 받아서 배열 바꿈
                                    - 데이터 복사하지 않고 원래 데이터에 대한 뷰를 반환

In [8]:
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [9]:
arr.swapaxes(1,2)

array([[[ 0,  4],
        [ 1,  5],
        [ 2,  6],
        [ 3,  7]],

       [[ 8, 12],
        [ 9, 13],
        [10, 14],
        [11, 15]]])

참고 자료
> Python for Data Analysis(2019), 한빛미디어