### Numpy ndarray : 다차원 배열 객체

- Numpy ndarray : (모든 원소가 같은 자료형을 가진)데이터를 담을 수 있는 N차원의 배열 객체, 
                                  파이썬에서 사용할 수 있는 대규모 데이터 집합을 담을 수 있는 빠르고 유연한 자료구조
- 스칼라 원소 간의 연산에 사용하는 문법과 비슷한 방식을 사용하여 전체 데이터 블록에 수학적 연산 수행

In [1]:
data = np.random.randn(2, 3)

data

array([[-0.97557416, -0.24643867, -1.00129281],
       [ 1.35619265,  0.65726373,  0.49047776]])

In [2]:
data *10

array([[ -9.75574159,  -2.46438666, -10.01292812],
       [ 13.56192647,   6.57263729,   4.90477758]])

In [3]:
data + data

array([[-1.95114832, -0.49287733, -2.00258562],
       [ 2.71238529,  1.31452746,  0.98095552]])

- `shape` : 차원의 크기를 튜플로 표현
- `dtype` : 파일에 저장된 자료형 표현

In [4]:
data.shape

(2, 3)

In [5]:
data.dtype

dtype('float64')

참고 자료
> Python for Data Analysis(2019), 한빛미디어