### 배열 연산으로 조건절 표현

- numpy.where : x if 조건 else y 같은 삼항식의 벡터화 버젼

In [1]:
xarr = np.array([1.1, 1.2,  1.3, 1.4, 1.5])
yarr = np.array([2.1, 2.2,  2.3, 2.4, 2.5])
cond = np.array([True, False, True, True, False])

In [2]:
# cond값이 True일때 xarr 가지고 아닐때는 yarr값 가지는 리스트 표기법

# 방법 1
result = [(x if c else y)
         for x, y, c in zip(xarr, yarr, cond)]
result

[1.1, 2.2, 1.3, 1.4, 2.5]

In [3]:
# 방법 2
result = np.where(cond, xarr, yarr)
result

array([1.1, 2.2, 1.3, 1.4, 2.5])

- np.where :
    - 2,3번째 인자는 배열이 아니여도 됨, 둘 중 혹은 둘 다 스칼라값이어도 가능
    - 데이터 분석에서 일반적인 where의 사용은 다른 배열에 기반한 새로운 배열 생성함.

In [4]:
# 임의로 생성된 데이터가 들어있는 행렬이 있고 양수는 모두 2로, 음수는 모두 -2로 처리
arr = np.random.randn(4, 4)

arr

array([[-1.10831613e+00, -1.02007106e+00,  7.98316516e-01,
         1.56223647e-01],
       [ 1.43292763e-03,  9.10780005e-02, -1.09376328e+00,
        -1.28291065e-03],
       [-3.46122770e-01,  1.19176537e+00, -3.17295787e-01,
         7.42959103e-01],
       [ 1.06800475e+00, -1.07463244e+00, -3.77610955e-01,
        -1.71546209e+00]])

In [5]:
arr > 0

array([[False, False,  True,  True],
       [ True,  True, False, False],
       [False,  True, False,  True],
       [ True, False, False, False]])

In [6]:
np.where( arr > 0, 2, -2)

array([[-2, -2,  2,  2],
       [ 2,  2, -2, -2],
       [-2,  2, -2,  2],
       [ 2, -2, -2, -2]])

- np.where : 
    - 스칼라값과 배열을 조합할 수 있음. 
    - np.where로 넘기는 배열은 그냥 크기만 같은 배열이거나 스칼라값이 될 수 있음

In [7]:
# arr의 모든 양수를 2로 바꿈
np.where(arr>0, 2, arr)  # 양수인 경우에만 2를 대입

array([[-1.10831613e+00, -1.02007106e+00,  2.00000000e+00,
         2.00000000e+00],
       [ 2.00000000e+00,  2.00000000e+00, -1.09376328e+00,
        -1.28291065e-03],
       [-3.46122770e-01,  2.00000000e+00, -3.17295787e-01,
         2.00000000e+00],
       [ 2.00000000e+00, -1.07463244e+00, -3.77610955e-01,
        -1.71546209e+00]])

참고 자료
> Python for Data Analysis(2019), 한빛미디어  