### sort

In [1]:
arr = np.random.randn(6)
arr

array([-0.96664338, -1.28233955, -0.95000469,  0.9127668 , -1.12437334,
        0.61627389])

In [2]:
arr.sort()
arr

array([-1.28233955, -1.12437334, -0.96664338, -0.95000469,  0.61627389,
        0.9127668 ])

- 다차원 배열의 정렬을 sort메서드에 넘긴 축의 값에 따라 1차원 정렬

In [3]:
arr = np.random.randn(5,3)
arr

array([[-0.68863632, -1.9901854 , -2.43812273],
       [-0.93258815,  0.88391199, -0.8199377 ],
       [ 0.03153378,  0.11516506,  1.35911483],
       [-2.36730398,  0.71858176,  0.9235594 ],
       [-1.20119655, -0.45234023,  1.02827203]])

In [4]:
arr.sort(1)
arr

array([[-2.43812273, -1.9901854 , -0.68863632],
       [-0.93258815, -0.8199377 ,  0.88391199],
       [ 0.03153378,  0.11516506,  1.35911483],
       [-2.36730398,  0.71858176,  0.9235594 ],
       [-1.20119655, -0.45234023,  1.02827203]])

`sort`메서드 :  배열을 직접 변경하지 않고 정렬된 결과 가지는 복사본 반환함.   
배열의 분위수를 구하는 쉽고 빠른 방법은 우선 배열 정렬 후 특정 분위의 값을 선택하는 것

In [5]:
large_arr = np.random.randn(1000)

large_arr.sort()
large_arr

array([-4.40482167e+00, -3.98726338e+00, -2.76033291e+00, -2.74487759e+00,
       -2.64329593e+00, -2.54021508e+00, -2.48778447e+00, -2.40423070e+00,
       -2.38136346e+00, -2.26921333e+00, -2.26116455e+00, -2.25550761e+00,
       -2.21009012e+00, -2.17609370e+00, -2.14890907e+00, -2.05049016e+00,
       -2.04503508e+00, -1.98802498e+00, -1.97834903e+00, -1.95899261e+00,
       -1.92152745e+00, -1.89751373e+00, -1.87054387e+00, -1.85846561e+00,
       -1.79194106e+00, -1.79128900e+00, -1.79074797e+00, -1.78517166e+00,
       -1.76867504e+00, -1.76518933e+00, -1.75013259e+00, -1.74542881e+00,
       -1.74368248e+00, -1.69674746e+00, -1.67950668e+00, -1.67218759e+00,
       -1.67083661e+00, -1.66613573e+00, -1.65965689e+00, -1.64811242e+00,
       -1.64741954e+00, -1.64590648e+00, -1.63740797e+00, -1.61714209e+00,
       -1.61644795e+00, -1.61240575e+00, -1.60667272e+00, -1.60476089e+00,
       -1.59889544e+00, -1.59555931e+00, -1.59386126e+00, -1.57526327e+00,
       -1.56821940e+00, -

In [6]:
large_arr[int(0.05 * len(large_arr))]  # 5% 분위수

-1.593861263895636

### algebra of sets

- `np.unique` : 배열 내 중복된 원소를 제거하고 남은 원소를 정렬된 형태로 반환. 가장 자주 사용

In [7]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob',  'Will','Joe', 'Joe'])

np.unique(names)

array(['Bob', 'Joe', 'Will'], dtype='<U4')

In [8]:
# 위의 것을 파이썬으로 구현하면,
sorted(set(names))

['Bob', 'Joe', 'Will']

In [9]:
ints = np.array([3,3,3,3,4,4,2,2,1,1])

np.unique(ints)

array([1, 2, 3, 4])

- `np.in1d` : 두개의 배열을 인자로 받아서 첫번째 배열의 원소가 두번째 배열의 원소를 포함하는지 나타내는 불리언 배열 반환

In [10]:
values = np.array([6,0,0,3,2,5,6])

np.in1d(values, [2,3,6])

array([ True, False, False,  True,  True, False,  True])

- 배열 집합 연산

|메서드|설명|
|:--|:--|
|unique(x)|배열 x에서 중복된 원소를 제거한 뒤 정렬하여 반환|
|intersect1d(x,y)|배열 x에서 y에 공통적으로 존재하는 원소를 정렬하여 반환|
|union1d(x,y)|두 배열의 합집합 반환|
|in1d(x,y)|x의 원소가 y의 원소에 포함되는지 나타내는 불리언 배열 반환|
|setdiff1d(x,y)|x와 y의 차집합 반환|
|setxor1d(x,y)|한 배열에는 포함되지만 두 배열 모두에는 포함되지 않는 원소들의 집합인 대칭차집합 반환|

### 배열 데이터의 파일 입출력

- Numpy로 디스크에서 텍스트나 바이너리 형식의 데이터 불러오거나 저장 가능
- 대부분의 경우 pandas 또는 다른 도구 사용하는 것 선호함

- `np.save`, `np.load` : 
    - 배열 데이터를 효과적으로 디스크에 저장하고 불러옴. 
    - 배열은 기본적으로 압축되지 않은 원시바이너리 형식의 `.npy`파일로 저장
    - 저장되는 파일 경로가 `.npy`로 끝나지 않으면 자동으로 확장자 추가됨. 이렇게 저장된 배열은 `np.load`로 불러올 수 없음

In [11]:
arr = np.arange(10)

np.save('some_array', arr)

In [12]:
np.load('some_array.npy')

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

- `np.savez` : 여러 개의 배열을 압축된 형태로 저장. 배열을 키워드 인자 형태로 전달함

In [13]:
np.savez('array_archive.npz', a = arr, b= arr)

- `npz`파일을 불러올 때는 각 배열을 필요할 때 불러오도록 사전 형식의 객체에 저장

In [14]:
arch = np.load('array_archive.npz')

arch['b']

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

- `numpy.savez_compressed` : 압축 잘되는 형식의 데이터에서 사용

In [15]:
np.savez_compressed('arrays_compressed.npz', a = arr, b= arr)

참고 자료
> Python for Data Analysis(2019), 한빛미디어  