#### 색인과 슬라이싱 기초

- 데이터 색인은 파이썬의 리스트와 유사하게 동작

In [1]:
arr = np.arange(10)

arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
arr[0]

0

In [5]:
arr[5:8]

array([5, 6, 7])

In [7]:
# 브로드캐스팅
arr[5:8] =12
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

- 리스트와의 중요한 차이점 : 배열 조각은 원본 배열의 뷰임. 즉, 데이터는 복사되지 않고 뷰에 대한 변경은 그대로 원본 배열에 반영
                                              -> 뷰 변경으로 원본도 같이 변경됨
- `copy()` : 뷰 대신 ndarray슬라이스의 복사본 얻고 싶을때는 위의 경우에는, 'arr[5:8].copy()'하면 명시적으로 배열 복사 가능

In [8]:
arr_slice = arr[5:8]
arr_slice

array([12, 12, 12])

In [9]:
arr_slice[1] = 12345

In [10]:
arr

array([    0,     1,     2,     3,     4,    12, 12345,    12,     8,
           9])

In [11]:
arr_slice[:] = 64

In [12]:
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

- 다차원 배열

In [13]:
arr2d = np.array([[1,2,3], [4,5,6],[7,8,9]])

arr2d[2]

array([7, 8, 9])

In [14]:
arr2d[0][2] # 행, 열

3

In [15]:
arr2d[0,2]

3

- 이전 값 복구

In [22]:
arr3d = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])

arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [23]:
arr3d[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [24]:
old_values = arr3d[0].copy()

In [25]:
arr3d[0] = 42

In [26]:
arr3d

array([[[42, 42, 42],
        [42, 42, 42]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [27]:
arr3d[0] = old_values

In [28]:
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [29]:
arr3d[1,0]

array([7, 8, 9])

#### 슬라이스로 선택

In [30]:
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [31]:
arr[1:6]

array([ 1,  2,  3,  4, 64])

In [32]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [34]:
arr2d[0]

array([1, 2, 3])

In [33]:
arr2d[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [35]:
arr2d[:2, 1:]

array([[2, 3],
       [5, 6]])

- 슬라이싱을 하면 항상 같은 차원의 배열에 대한 뷰 얻음
- 정수 색인과 슬라이스를 함께 사용해서 한차원 낮은 슬라이스 얻을  수 있음

In [36]:
# 2번째 로우에서 처음 2칼럼만 선택

arr2d[1, :2]

array([4, 5])

In [40]:
# 1-2째 로우에서 3번째 칼럼만 선택

arr2d[:2, 2]

array([3, 6])

In [42]:
arr2d[:, :1]

array([[1],
       [4],
       [7]])

In [44]:
arr2d[:2, 1:] = 0

arr2d

array([[1, 0, 0],
       [4, 0, 0],
       [7, 8, 9]])

참고 자료
> Python for Data Analysis(2019), 한빛미디어