### 수학 메서드와 통계 메서드

- 배열 전체 혹은 배열의 한축의 자료에 대한 통계를 계산하는 수학 함수는 배열 메서드로 사용 가능
- 전체 합(sum), 평균(mean), 표준편차(std)는 numpy의 최상위 함수를 이용하거나 배열의 인스턴스 메서드를 사용해서 구할 수 있음

In [1]:
arr = np.arange(0, 32).reshape([4,2,4])
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]],

       [[16, 17, 18, 19],
        [20, 21, 22, 23]],

       [[24, 25, 26, 27],
        [28, 29, 30, 31]]])

- mean, sum은 선택적으로 axis 인자 받아서 해당 axis에 대한 통계를 계산하고 한차수 낮은 배열 반환

![image.png](https://taewanmerepo.github.io/2017/09/numpy_axis/axis.jpg)

- **axis=None** : 모든 요소의 값을 합산하여 1개을 스칼라값으로 반환

In [2]:
arr.mean()

15.5

In [3]:
np.mean(arr)

15.5

In [4]:
arr.sum()

496

- **axis = 0** : x축 기준으로 여러 row를 1개로 합치는 과정

In [5]:
arr.sum(axis=0)

array([[48, 52, 56, 60],
       [64, 68, 72, 76]])

![image.png](https://taewanmerepo.github.io/2017/09/numpy_axis/axis0-cube.jpg)

![image.png](https://taewanmerepo.github.io/2017/09/numpy_axis/axis0.png)

axis=0 : 
가장 외각의 괄호를 제거하는 과정으로 생각하면 됨. 위와  같이 가장 외각의 괄호를 제거하고, 각 row에 데이터는 위치별로 합산. 
결과적으로 컬럼과 depth의 위치별 합이 계산됨.

- **axis=1**:  y축을 기준으로 row별로 존재하는 column들 값을 1개로 축소. y축 즉 컬럼을 합치는 합산. 

shape이 (4, 2, 4)인 데이터를 y축을 기준으로 합산하면 결과 shape은 컬럼을 제거한 (4, 4)가 반환. 각 row의 2개의 컴럼이 1개로 축소됨

In [6]:
arr.sum(axis=1)

array([[ 4,  6,  8, 10],
       [20, 22, 24, 26],
       [36, 38, 40, 42],
       [52, 54, 56, 58]])

![image.png](https://taewanmerepo.github.io/2017/09/numpy_axis/axis1-cube.jpg)

![image.png](https://taewanmerepo.github.io/2017/09/numpy_axis/axis1.png)

axis=1 :  가장 외각에서 두 번째 괄호를 제거. 위와 같이 각 row에서 컬럼을 구분하는 괄호를 제거하고, 각 컬럼의 데이터는 위치별로 합산. 결과적으로 row 별로 컬럼들의 depth 위치별 합이 계산됨

- **axis=2** : z축을 기준으로 column의 depth가 가진 값을 축소하는 과정.  z축 dpeth 요소를 합치는 연산. 

shape이 (4, 2, 4)인 데이터를 z축을 기준으로 합산하면 결과 shape은 depth를 제거한 (4, 2)가 반환. 각 컬럼의 depth는 1개의 스칼라값으로 변환됨

In [7]:
arr.sum(axis=2)

array([[  6,  22],
       [ 38,  54],
       [ 70,  86],
       [102, 118]])

![image.png](https://taewanmerepo.github.io/2017/09/numpy_axis/axis2-cube.jpg)

![image.png](https://taewanmerepo.github.io/2017/09/numpy_axis/axis2.png)

axis=2 : depth를 묶는 괄호를 제거. 위와 같이 각 column에서 Depth를 구분하는 괄호를 제거하고, 모든 Depth 요소를 합산. 결과적으로 예제에서 각 row의 컬럼들은 1개의 스칼라값으로 변환함

In [8]:
arr.mean(axis=1) 

array([[ 2.,  3.,  4.,  5.],
       [10., 11., 12., 13.],
       [18., 19., 20., 21.],
       [26., 27., 28., 29.]])

In [9]:
arr= np.random.randn(5,4)
arr

array([[ 0.92424365, -0.05903619,  0.45926123, -1.23651603],
       [-0.48793703, -1.85780293,  0.09680494,  0.42031649],
       [ 0.58001308,  0.34758113, -0.73603482,  0.15163727],
       [-0.02097313, -2.49776869, -0.28850793, -0.15310245],
       [-0.80345158, -0.66143591,  2.25783496,  0.80276558]])

In [10]:
arr.mean()

-0.1381054172871518

In [11]:
np.mean(arr)

-0.1381054172871518

In [12]:
arr.sum()

-2.762108345743036

In [13]:
arr.mean(axis=1)

array([ 0.02198817, -0.45715463,  0.08579916, -0.74008805,  0.39892826])

In [14]:
arr.sum(axis=0)

array([ 0.19189499, -4.72846259,  1.7893584 , -0.01489914])

- `cumsum`, `cumprod` : 중간 계산 값 담는 배열 반환

In [15]:
arr = np.array([1,2,3,4,5,6,7])

arr.cumsum()

array([ 1,  3,  6, 10, 15, 21, 28])

- `cumsum` : 같은 크기의 배열 반환하나, 축 지정하여 부분적으로 계산하면 낮은 차수의 슬라이스 반환함

In [16]:
arr = np.array([[0,1,2], [3,4,5], [6,7,8]])

arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [17]:
arr.cumsum(axis = 0)

array([[ 0,  1,  2],
       [ 3,  5,  7],
       [ 9, 12, 15]])

In [18]:
arr.cumprod(axis=1)

array([[  0,   0,   0],
       [  3,  12,  60],
       [  6,  42, 336]])

- 기본 배열 통계 메서드

|메서드|설명|
|:--|:--|
|sum|배열 전체 혹은 특정 축에 대한 모든 원소의 합 계산. 크기가 0인 배열에 대한 sum결과는 0|
|mean|산술 평균을 구함. 크기가 0인 배열에 대한 mean 결과는 NaN|
|std, var|각각 표준편차(std)와 분산(var)구함. 선택적으로 지유도를 줄 수 있으며 분모의 기본값은 n임|
|min, max|최소값, 최대값|
|argmin, argmax|최소 원소의 색인값과 최대 원소의 색인값|
|cumsum|각 원소의 누적값|
|cumprod|각 원소의 누적곱|

### 불리언 배열을 위한 메서드

- boolean값을 1(True) 또는 0(False)로 강제 가능
- sum메서드 실행하면 boolean인 원소의 갯수 셀 수 있음

In [19]:
arr = np.random.randn(100)

In [20]:
(arr > 0).sum()

43

- `any` 메서드 : 하나 이상의 값이 True인지 검사
- `all`메서드: 모든 원소가 True인지 검사

- `any`, `all`메서드 : boolean 배열에 유용. boolean배열이 아니어도 동작하며 0아닌 원소는 모두 True로 간주됨

In [21]:
bools = np.array([False, False, True, False])

bools.any()

True

In [22]:
bools.all()

False

참고 자료
> Python for Data Analysis(2019), 한빛미디어  
> [Numpy에서 np.sum 함수의 axis 이해](http://taewan.kim/post/numpy_sum_axis/)