#### 유니버셜 함수 : 배열의 각 원소를 빠르게 처리하는 함수

- `ufunc` : 
    - 유니버셜 함수
    - ndarray안에 있는 데이터 원소별로 연산을 수행
    - 하나 이상의 스칼라 값을 받아서 하나 이상의 스칼라 결과값을 반환하는 간단한 함수를 고속으로 수행하는 벡터화된 래퍼 함수
    - 많은 ufunc는 `sqrt`나 `exp` 같은 간단한 변형을 전체 원소에 적용 가능

- 단항 유니버셜 함수 

In [1]:
arr = np.arange(10)

arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [2]:
np.sqrt(arr)  # sqrt : 제곱근(루트)을 계산

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [3]:
np.exp(arr) # exp : 지수를 계산

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

- 이향 유니버셜 함수 : 2개 인자를 취해 단일 배열을 반환하는 함수. 예) add, maximun

In [4]:
x = np.random.randn(8)
y = np.random.randn(8)

In [5]:
x

array([-0.15990332,  1.1909553 , -1.79216591, -0.63382526,  0.89270505,
       -0.69899101,  1.31738458, -0.10359897])

In [6]:
y

array([-1.11119864,  1.40664653, -2.03291066, -1.05345129,  1.69598676,
       -0.0577022 ,  0.52414219,  0.7302534 ])

In [7]:
np.maximum(x, y) # x, y 의 같은 위치에서의 최대값을 배열로 출력

array([-0.15990332,  1.40664653, -1.79216591, -0.63382526,  1.69598676,
       -0.0577022 ,  1.31738458,  0.7302534 ])

- `modf` : 파이썬 내장함수인 `divmod`의 벡터화 버전. 분수를 받아서 몫과 나머지 함께 반환

In [9]:
arr = np.random.randn(7) * 5
arr

array([-5.32921971, -2.97664971,  3.99893798, -1.95782649, -9.95167616,
        5.59790676,  3.18158622])

In [10]:
remainder, whole_part = np.modf(arr)

In [11]:
remainder

array([-0.32921971, -0.97664971,  0.99893798, -0.95782649, -0.95167616,
        0.59790676,  0.18158622])

In [12]:
whole_part

array([-5., -2.,  3., -1., -9.,  5.,  3.])

- `out` : 선택적으로 `out`인자를 취하여 계산 결과를 따로 저장 가능

In [13]:
arr

array([-5.32921971, -2.97664971,  3.99893798, -1.95782649, -9.95167616,
        5.59790676,  3.18158622])

In [14]:
np.sqrt(arr)

array([       nan,        nan, 1.99973448,        nan,        nan,
       2.36598959, 1.78370015])

In [15]:
np.sqrt(arr, arr)

array([       nan,        nan, 1.99973448,        nan,        nan,
       2.36598959, 1.78370015])

In [16]:
arr

array([       nan,        nan, 1.99973448,        nan,        nan,
       2.36598959, 1.78370015])

- 단항 유니버셜 함수

|함수|설명|
|:--|:--|
|abs, fabs|각 원소(정수, 부동소수점수, 복소수)의 절대값. 복소수가 아닌 경우에 빠른 연산을 위해 fabs사용|
|sqrt|각 원소의 제곱근. arr ** 0.5와 동일|
|square|각 원소의 제곱. arr\*\*2와 동일|
|exp|각 원소의 지수 'e'|
|log, log10, log2, log1p|각각 자연로그, 로그 10, 로그 2, 로그(1+x)|
|sign|각원소의 부호 계산. 1(양수), 0(영), -1(음수)|
|ceil|각 원소의 소수자리 올림. 각 원소의 값보다 길거나 큰 정수 중 가장 작은 정수 반환|
|floor|각 원소의 소수자리 내림. 각 원소의 값보다 적거나 같은 정수 중 가장 작은 정수 반환|
|rint|각 원소의 소수자리를 반올림. dtype은 유지|
|modf|각 원소의 몫과 나머지를 각각의 배열로 반환|
|isnan|각 원소가 숫자가 아닌지(NaN, Not a Number)를 나타내는 불리언 배열 반환|
|isfinite, isinf|각각 배열의 각 원소가 유한한지(non-inf, non-NaN), 무한한지 불리언 배열로 반환|
|cos, cosh, sin, sinh, tan, tanh|일반 삼각함수의 쌍곡삼각함수|
|arccos, arccosh, arcsin, arcsinh, arctan, arctanh|역삼각함수|
|logical_not|각 원소의 논리 부정(not)값을 계산함. -arr과 동일|

- 이항 유니버셜 함수

|함수|설명|
|:--|:--|
|add|두 배열에서 같은 위치의 원소끼리 더함|
|subtract|첫번째 배열의 원소에서 두번째 배열의 원소를 뺌|
|multiply|배열의 원소끼리 곱함|
|divide, floor_divide|첫번째 배열의 원소를 두번째 배열의 원소로 나눔. floor_divide는 몫만 취함|
|power|첫번째 배열의 원소를 두번째 배열의 원소만큼 제곱|
|maximum, fmax|각 배열의 두 원소 중 큰 값을 반환. fmax는 NaN을 무시함|
|minimum, fmin|각 배열의 두 원소 중 작은 값을 반환. fmin은 NaN을 무시함|
|mod|첫번째 배열의 원소를 두번째 배열의 원소로 나눈 나머지를 구함|
|copysign|첫번째 배열의 원소의 기호를 두번째 배열의 원소의 기호로 바꿈|
|greater, greater_equal, less, less_equal, equal, not_equal|각각 두 원소간의 >,>=,<=,==,!= 비교연산 결과를 불리언 배열로 반환|
|logical_and, logical_or, logical_xor|각각 두 원소 간의 &,\|,\^ 논리 연산 결과를 반환|

참고 자료
> Python for Data Analysis(2019), 한빛미디어