#### Numpy배열의 산술연산

- 벡터화 : 배열의 경우, for문 작성없이 데이터를 일괄 처리 가능, 같은 크기의 배열 간의 산술연산은 배열의 각 원소 단위로 적용됨

In [1]:
arr = np.array([[1., 2., 3.],[4., 5., 6.]])

arr

array([[1., 2., 3.],
       [4., 5., 6.]])

In [2]:
arr * arr

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [3]:
arr - arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [4]:
1/ arr

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [5]:
arr ** 0.5

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

- 불리언 배열 : 같은 크기를 가지는 배열 간의 비교연산

In [6]:
arr2 = np.array([[0., 4., 1.], [7., 2., 12.]])

arr2

array([[ 0.,  4.,  1.],
       [ 7.,  2., 12.]])

In [7]:
arr2 > arr

array([[False,  True, False],
       [ True, False,  True]])

- 브로드캐스팅 : 크기가 다른 배열 간 연산

참고 자료
> Python for Data Analysis(2019), 한빛미디어