#### 불리언 값으로 선택

In [1]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

In [2]:
# 임의의 표준 정규 분포 데이터 생성
data = np.random.randn(7, 4)

In [3]:
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [4]:
data

array([[ 0.00474053,  0.07263022, -0.22637132,  0.39514556],
       [ 0.2680827 , -0.89234979,  0.24818708, -0.71036144],
       [ 1.57679079, -0.66200879, -1.32893314,  1.24322345],
       [ 1.55609495,  0.14352253,  1.55341286,  2.97112087],
       [ 0.51866125,  2.32063859,  0.51642698, -0.98623244],
       [-0.84509488,  0.81854967, -0.5468766 , -1.59545648],
       [-1.18607899,  0.3415907 ,  0.45750172,  0.67868081]])

In [5]:
names == 'Bob'

array([ True, False, False,  True, False, False, False])

- `names == 'Bob'`가 True/False 여부로 선택하도록 함

In [6]:
 # True인것 선택

data[names == 'Bob'] 

array([[ 0.00474053,  0.07263022, -0.22637132,  0.39514556],
       [ 1.55609495,  0.14352253,  1.55341286,  2.97112087]])

In [7]:
data[names == 'Bob', 2:]

array([[-0.22637132,  0.39514556],
       [ 1.55341286,  2.97112087]])

In [8]:
data[names == 'Bob', 3]

array([0.39514556, 2.97112087])

In [9]:
# 위의 조건과 반대되도록

names != 'Bob'

array([False,  True,  True, False,  True,  True,  True])

- `~` : 일반적인 조건을 반대로 사용

In [10]:
data[~(names =='Bob')]

array([[ 0.2680827 , -0.89234979,  0.24818708, -0.71036144],
       [ 1.57679079, -0.66200879, -1.32893314,  1.24322345],
       [ 0.51866125,  2.32063859,  0.51642698, -0.98623244],
       [-0.84509488,  0.81854967, -0.5468766 , -1.59545648],
       [-1.18607899,  0.3415907 ,  0.45750172,  0.67868081]])

- 3가지 이름 중에 2가지 이름 선택 : `&(and)`나 `|(or)`같은 논리 연산자 사용한 여러 개의 `불리언` 조건 사용

In [12]:
mask = (names =="Bob") | (names == 'Will')

mask

array([ True, False,  True,  True,  True, False, False])

In [13]:
data[mask]

array([[ 0.00474053,  0.07263022, -0.22637132,  0.39514556],
       [ 1.57679079, -0.66200879, -1.32893314,  1.24322345],
       [ 1.55609495,  0.14352253,  1.55341286,  2.97112087],
       [ 0.51866125,  2.32063859,  0.51642698, -0.98623244]])

 - 배열에 불리언 색인 이용해서 데이터를 선택하면 반환되는 배열의 내용이 바뀌지 않더라도 항상 데이터 복사 발생함

In [14]:
data[data < 0] = 0

data

array([[0.00474053, 0.07263022, 0.        , 0.39514556],
       [0.2680827 , 0.        , 0.24818708, 0.        ],
       [1.57679079, 0.        , 0.        , 1.24322345],
       [1.55609495, 0.14352253, 1.55341286, 2.97112087],
       [0.51866125, 2.32063859, 0.51642698, 0.        ],
       [0.        , 0.81854967, 0.        , 0.        ],
       [0.        , 0.3415907 , 0.45750172, 0.67868081]])

In [15]:
data[names != 'Joe'] = 7

data

array([[7.        , 7.        , 7.        , 7.        ],
       [0.2680827 , 0.        , 0.24818708, 0.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [0.        , 0.81854967, 0.        , 0.        ],
       [0.        , 0.3415907 , 0.45750172, 0.67868081]])

참고 자료
> Python for Data Analysis(2019), 한빛미디어