### ndarray 생성

- array함수 이용 : 배열 생성의 가장 쉬운 방법 
- 순차적인 객체(다른 배열도 포함)를 넘고 받고, 넘겨 받은 데이터가 있는 새로운 Numpy 배열 생성

In [1]:
data1 = [6, 7.5, 8, 0, 1]

arr1 = np.array(data1)
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [2]:
data2 = [[1,2,3,4],[5,6,7,8]]

arr2 = np.array(data2)
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

- `ndim` 
- `shape`

In [3]:
arr2.ndim

2

In [4]:
arr2.shape

(2, 4)

In [5]:
arr1.dtype

dtype('float64')

In [6]:
arr2.dtype

dtype('int64')

In [7]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [8]:
np.zeros((3, 6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [11]:
np.empty((2,3,2))

array([[[ 0.00000000e+000,  0.00000000e+000],
        [ 0.00000000e+000,  0.00000000e+000],
        [ 0.00000000e+000,  0.00000000e+000]],

       [[ 0.00000000e+000,  0.00000000e+000],
        [ 0.00000000e+000,  5.73728779e+174],
        [ 1.49166815e-154, -1.29074110e-231]]])

In [12]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

- 배열 생성 함수

|함수|설명|
|:---|:---|
|array|입력 데이터(리스트, 튜플, 배열 또는 다른 순차형 데이터)를 ndarray로 변환하여  dtype을 명시하지 않은 경우 자료형을 추론하여 저장.  기본적으로 입력 데이터는 복사함|
|asarray|입력 데이터를 ndarray로 변환하지만 입력 데이터가 이미 ndarray일 경우 복사가 일어나지 않음|
|arange|내장 range 함수와 유사하지만 리스트 대신 ndarray를 반환|
|ones, ones_like|주어진 dtype과 모양을 가지는 배열을 생성하고 내용을 모두 1로 초기화함. ones_like는 주어진 배열과 동일한 모양과 dtype을 가지는 배열을 모두 새로 생성한 내용을 모두 1로 초기화함|
|zeros, zeros_like|ones, ones_like와 동일하지만 내용을 0으로 채움|
|empty, empty_like|메모리에 할당하여 새로운 배열을 생성하나 ones나 zeros처럼 값을 초기화하지 않음|
|full, full_like|인자로 받은 dtype과 배열의 모양을 가지는 배열을 생성하고 인자로 받은 값으로 배열을 채움|
|eye, identity|NXN 크기의 단위 행렬 생성|


참고 자료
> Python for Data Analysis(2019), 한빛미디어