#### fancy indexing

- 정수 배열을 사용한 색인을 사용한 색인을 설명하기 위해 Numpy에서 차용한 단어

In [1]:
arr = np.empty((8,4))

for i in range(8):
    arr[i] = i
    
arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

- 특정 순서로 로우 선택

In [2]:
arr[[4,3,0,6]]

array([[4., 4., 4., 4.],
       [3., 3., 3., 3.],
       [0., 0., 0., 0.],
       [6., 6., 6., 6.]])

In [3]:
arr[[-3, -5, -7]]

array([[5., 5., 5., 5.],
       [3., 3., 3., 3.],
       [1., 1., 1., 1.]])

In [4]:
arr = np.arange(32).reshape((8,4))
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [5]:
arr[[1,5,7,2],[0,3,2,1]]  # 행, 열로 매칭되어 추출

array([ 4, 23, 30,  9])

In [6]:
arr[[1,5,7,2]][:, [0,3,1,2]] # 해당 로우 추출된 것에서 해당 데이터의 전체 row에서 column의 순서에 맞게 출력됨

array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30],
       [ 8, 11,  9, 10]])

참고 자료
> Python for Data Analysis(2019), 한빛미디어